# -*- coding: utf-8 -*-
"""
Created on 2023-12-19 21:28:19
---------
@summary:
---------
@author: poppies
"""

from feapder import Item


class DoubanFeapderItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i douban_feapder
    """

    __table_name__ = "douban_feapder"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.title = None
        self.score = None
        self.detail_url = None
        self.detail_text = None
