# -*- coding: utf-8 -*-
"""
Created on 2023-12-21 20:52:02
---------
@summary:
---------
@author: poppies
"""

from feapder import Item


class WpShopInfoItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i wp_shop_info
    """

    __table_name__ = "wp_shop_info"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.price = None
        self.title = None
